apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: awesome-applications
spec:
  destination:
    name: in-cluster
    namespace: argocd
  project: default
  source:
    path: environments/dev/awesome-applications
    repoURL: https://github.com/iaingalloway/awesome-argo.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
